version: '3'

services:
  app-base:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    environment:
      DEV_PLATFORM: DOCKER
      NODE_GLOBAL_ENV: /app/.env
    develop:
      watch:
        - action: sync+restart
          path: ./libs
          target: /app/libs/
        - action: rebuild
          path: ./package.json
          target: /app/package.json
    volumes:
      - mono-node-modules:/app/node_modules
